version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "media-list"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-zzsnctts178w"
s3_prefix = "media-list"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
