AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  media-list

  SAM for media-list
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  MediaListFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: media-list/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Events:
        MediaList:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{cloud_name}/media/list/{proxy+}
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MediaListApi:
    Description: "API Gateway endpoint URL for Stage stage for media-list function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/{cloud_name}/media/list/{proxy+}"
  MediaListFunction:
    Description: "Media List Lambda Function ARN"
    Value: !GetAtt MediaListFunction.Arn
  MediaListFunctionIamRole:
    Description: "Implicit IAM Role created for Media List function"
    Value: !GetAtt MediaListFunctionRole.Arn
